app/teacher/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, IntegerField, StringField, SubmitField, SelectField
from wtforms.validators import InputRequired, DataRequired, NumberRange
from flask_uploads import UploadSet
from flask_wtf.file import FileField, FileAllowed, FileRequired

upsr = UploadSet('files', extensions=('xls', 'xlsx', 'pdf', 'doc', 'docx', 'txt', 'zip', '7z', 'rar'))
up_corrected = UploadSet('files', extensions=('zip', 'rar'))


class CourseForm(FlaskForm):
    outline = TextAreaField('课程大纲', validators=[InputRequired()])
    outlet_attachment = FileField('大纲附件')
    teamsize_max = IntegerField('课程人数上限', validators=[DataRequired(), NumberRange(min=1, message='至少需要一个人')])
    teamsize_min = IntegerField('课程人数下限', validators=[DataRequired(), NumberRange(min=1, message='至少需要一个人')])
    no_miss = IntegerField('全勤分数', validators=[InputRequired(), NumberRange(min=0, max=100, message='分数在0-100')])
    miss_1 = IntegerField('一次缺勤', validators=[InputRequired(), NumberRange(min=0, max=100, message='分数在0-100')])
    miss_2 = IntegerField('两次缺勤', validators=[InputRequired(), NumberRange(min=0, max=100, message='分数在0-100')])
    miss_3 = IntegerField('三次缺勤', validators=[InputRequired(), NumberRange(min=0, max=100, message='分数在0-100')])
    miss_4 = IntegerField('四次缺勤', validators=[InputRequired(), NumberRange(min=0, max=100, message='分数在0-100')])
    miss_5 = IntegerField('五次及以上缺勤', validators=[InputRequired(), NumberRange(min=0, max=100, message='分数在0-100')])

    def validate(self):
        if not super(CourseForm, self).validate():
            return False
        if not self.teamsize_min.data <= self.teamsize_max.data:
            self.teamsize_min.errors.append('下限人数不多于上限')
            self.teamsize_max.errors.append('上限人数不少于下限')
            return False
        return True


class HomeworkForm(FlaskForm):
    name = StringField('作业名', validators=[DataRequired()])
    base_requirement = TextAreaField('作业要求', validators=[DataRequired()])
    time = StringField('持续时间', validators=[DataRequired()])
    weight = IntegerField('权重', validators=[DataRequired()])
    max_submit_attempts = IntegerField('最大提交次数', validators=[DataRequired()])


class UploadResourceForm(FlaskForm):
    up = FileField(validators=[
        FileAllowed(upsr, u'xls, xlsx, pdf, doc, docx, txt, zip, 7z, rar'),
        FileRequired(u'文件未选择!')])
    submit = SubmitField(u'上传')


class UploadCorrected(FlaskForm):
    up_corrected = FileField(validators=[FileAllowed(up_corrected, u'zip and rar only'),
                                         FileRequired(u'文件未选择!')])
    submit = SubmitField(u'上传')


class AcceptTeam(FlaskForm):
    id = IntegerField(validators=[InputRequired()])
    # button = SubmitField('通过')


class RejectTeam(FlaskForm):
    id = IntegerField(validators=[InputRequired()])
    # button = SubmitField('拒绝')
    reason = TextAreaField('拒绝理由', validators=[InputRequired()])


class MoveForm(FlaskForm):
    student = IntegerField('学生id', validators=[DataRequired()])
    pending_teams = SelectField('可以加入的组',
                                choices=[],
                                coerce=int)


class AttendanceForm(FlaskForm):
    info = StringField("备注")
    time_delta = IntegerField("签到开放时长")


class PlusForm(FlaskForm):
    name = StringField('加分项名', validators=[DataRequired()])
    weight = StringField('加分最大分值', validators=[DataRequired()])

app/teacher/__init__.py
from flask import Blueprint

teacher = Blueprint('teacher', __name__)

from . import views

app/teacher/views.py
import shutil
import os
import zipfile
import json
from flask import flash, redirect, render_template, url_for, request,\
    current_app, send_from_directory, make_response, send_file
from datetime import datetime, timedelta
from flask_login import login_required, current_user
from ..upload_utils import secure_filename
from . import teacher
from ..auths import UserAuth
from .forms import *
from ..models.models import *
from flask_uploads import UploadNotAllowed
from openpyxl.utils.exceptions import InvalidFileException
from config import basedir
from openpyxl import Workbook
from sqlalchemy import not_


@teacher.before_request
@login_required
def before_request():
    pass


@teacher.route('/')
def index():
    courses = Teacher.query.filter_by(id=current_user.id).first().courses
    return render_template('teacher/index.html', courses=courses)


def download_file(directory, filename):
    response = make_response(send_from_directory(directory, filename, as_attachment=True))
    response.headers["Content-Disposition"] = "attachment; filename={}".format(filename.encode().decode('latin-1'))
    return response


@teacher.route('/<course_id>/course', methods=['GET', 'POST'])
@UserAuth.teacher_course_access
def set_course_info(course_id):
    # 教师课程信息
    form = CourseForm()
    course = Course.query.filter_by(id=course_id).first()
    if form.validate_on_submit():
        course.outline = form.outline.data
        course.teamsize_min = form.teamsize_min.data
        course.teamsize_max = form.teamsize_max.data
        course.no_miss = form.no_miss.data
        course.miss_1 = form.miss_1.data
        course.miss_2 = form.miss_2.data
        course.miss_3 = form.miss_3.data
        course.miss_4 = form.miss_4.data
        course.miss_5 = form.miss_5.data
        db.session.add(course)
        db.session.commit()

        if form.outlet_attachment.data:
            file = form.outlet_attachment.data
            filename = secure_filename(file.filename)
            filedir = os.path.join(basedir, 'uploads', str(course_id))
            # 总之有outlet就删了先。。
            for file_ in os.listdir(filedir):
                try:
                    name, _ = file_.split('.')
                    if name == 'outlet':
                        os.remove(os.path.join(filedir, file_))
                except ValueError:
                    pass

            file.save(os.path.join(filedir, filename))
            _, ext = filename.split('.')
            os.rename(os.path.join(filedir, filename), os.path.join(filedir, 'outlet.' + ext))

        flash('修改成功！', 'success')
        return redirect(url_for('teacher.set_course_info', course_id=course_id))
    form.outline.data = course.outline
    form.teamsize_min.data = course.teamsize_min
    form.teamsize_max.data = course.teamsize_max
    form.no_miss.data = course.no_miss
    form.miss_1.data = course.miss_1
    form.miss_2.data = course.miss_2
    form.miss_3.data = course.miss_3
    form.miss_4.data = course.miss_4
    form.miss_5.data = course.miss_5
    outlet_attachment = None
    filedir = os.path.join(basedir, 'uploads', str(course_id))
    if not os.path.exists(filedir):
        os.mkdir(filedir)
    for file in os.listdir(filedir):
        try:
            name, _ = file.split('.')
            if name == 'outlet':
                outlet_attachment = file
                break
        except ValueError:
            pass
    if request.args.get('action') == 'download':
        return send_from_directory(filedir, outlet_attachment, as_attachment=True)
    return render_template('teacher/course.html', course_id=course_id, form=form, course=course, nav='set_course_info', outlet_attachment=outlet_attachment)


@teacher.route('/<course_id>/resource', methods=['GET', 'POST'])
@UserAuth.teacher_course_access
def manage_resource(course_id):
    # 教师查看修改课程资源
    path = request.args.get('path')
    if not path:
        return redirect(url_for('teacher.manage_resource', course_id=course_id, path='/'))

    expand_path = os.path.join(current_app.config['UPLOADED_FILES_DEST'], 'resource', course_id, path[1:])
    if not os.path.exists(expand_path):
        # 没有文件夹？赶紧新建一个，真鸡儿丢人
        os.mkdir(expand_path)

    if request.method == 'POST' and 'file' in request.files:
        # 上传文件
        file = request.files['file']
        filename = secure_filename(file.filename)
        filepath = os.path.join(current_app.config['UPLOADED_FILES_DEST'], 'resource', course_id, path[1:], filename)
        if os.path.exists(filepath):
            flash('已经存在了同名文件', 'danger')
            return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))
        file.save(filepath)
        flash('上传成功！', 'success')
        return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))

    if request.method == 'POST' and 'dirname' in request.form:
        # 新建文件夹
        dirname = request.form['dirname']
        dirpath = os.path.join(current_app.config['UPLOADED_FILES_DEST'], 'resource', course_id, path[1:], dirname)
        if os.path.exists(dirpath):
            flash('已经存在了同名文件夹', 'danger')
            return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))
        os.mkdir(dirpath)
        flash('新建文件夹成功！', 'success')
        return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))

    if 'action' in request.form:
        if request.form.get('action') == 'delete':
            # 删除
            filepath = os.path.join(
                current_app.config['UPLOADED_FILES_DEST'],
                'resource',
                course_id,
                path[1:],
                request.form.get('filename')
            )
            if not os.path.exists(filepath):
                flash('文件不存在！', 'danger')
                return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))
            if os.path.isfile(filepath):
                os.remove(filepath)
            else:
                shutil.rmtree(filepath)
            flash('删除成功！', 'success')
            return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))

    if request.args.get('download'):
        # 下载
        filedir = os.path.join(
            current_app.config['UPLOADED_FILES_DEST'],
            'resource',
            course_id,
            path[1:])
        filename = request.args.get('filename')
        print(filename)
        if os.path.exists(os.path.join(filedir, filename)):
            return download_file(filedir, filename)
        else:
            flash('文件不存在！', 'danger')
            return redirect(url_for('teacher.manage_resource', course_id=course_id, path=path))

    files = []

    def sizeof_fmt(num, suffix='B'):
        for unit in ['', 'K', 'M', 'G', 'T', 'P', 'E', 'Z']:
            if abs(num) < 1024.0:
                return "%3.1f%s%s" % (num, unit, suffix)
            num /= 1024.0
        return "%.1f%s%s" % (num, 'Y', suffix)

    class file_attributes:
        name = ""
        size = ""
        create_time = datetime.min
        is_dir = False
        is_file = False

        def __init__(self, name, size, create_time, is_dir, is_file):
            self.name = name
            self.size = size
            self.create_time = create_time
            self.is_dir = is_dir
            self.is_file = is_file

    for file in os.scandir(expand_path):
        time = datetime.fromtimestamp(file.stat().st_mtime)
        files.append(file_attributes(file.name, sizeof_fmt(file.stat().st_size), time, file.is_dir(), file.is_file()))
    return render_template('teacher/resource.html', course_id=course_id, files=files, path=path, nav='manage_resource')


@teacher.route('/<course_id>/homework', methods=['GET', 'POST'])
@UserAuth.teacher_course_access
def homework(course_id):

    form = HomeworkForm()

    if request.args.get('get_teamhomework_all'):
        return get_teamhomework_all(course_id)
    elif request.args.get('get_score_all'):
        return get_score_all(course_id)

    if form.validate_on_submit():
        if form.weight.data > 100 or form.weight.data <= 0:
            flash('无效的权重', 'danger')
            return redirect(url_for('teacher.homework', course_id=course_id))
        begin_time, end_time = form.time.data.split(' - ')
        begin_time = datetime.strptime(begin_time, '%m/%d/%Y %H:%M')
        end_time = datetime.strptime(end_time, '%m/%d/%Y %H:%M')
        homework = Homework()

        homework.name = form.name.data
        homework.base_requirement = form.base_requirement.data
        homework.begin_time = begin_time
        homework.end_time = end_time
        homework.weight = form.weight.data
        homework.max_submit_attempts = form.max_submit_attempts.data
        homework.course_id = course_id

        db.session.add(homework)
        db.session.commit()

        flash('发布成功！', 'success')
        return redirect(url_for('teacher.homework', course_id=course_id))
    course = Course.query.filter_by(id=course_id).first()

    homework_list = Homework.query.filter_by(course_id=course_id).all()
    return render_template('teacher/homework.html', course_id=course_id, homeworks=homework_list, form=form, course=course, nav='homework')


# PudgeG负责：提交情况表导出↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
@teacher.route('/<course_id>/homework/download', methods=['GET', 'POST'])
@UserAuth.teacher_course_access
def get_teamhomework_all(course_id):
    # 得到所有小队历次作业提交信息
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = '团队累计提交作业情况'

    team_list = Team.query.filter_by(course_id=course_id).filter_by(status=2).all()
    # Team.team_list(course_id)
    homework_list = Homework.query.filter_by(course_id=course_id).all()
    # Homework.homework_list(course_id)

    # 总列数
    column_number = 2
    # 总行数
    row_number = 1

    # 第一行输入的内容

app/templates/teacher/course.html
{% extends "base_main.html" %}

{% block title %}{{ super() }} - 课程管理{% endblock %}

{% block content_header %}
    <h1>{{ course.name }}：课程信息</h1>
{% endblock %}

{% block body_attribs %} class="hold-transition skin-black sidebar-mini" {% if form.errors %}onload="edit_state()"
{% endif %}{% endblock %}

{% block breadcrumb %}
    <li><a href="/"><i class="fa fa-dashboard"></i> 主页</a></li>
    <li class="active">课程信息</li>
{% endblock %}

{% block content_main %}
    <article>
        <div class="box box-{% if course.status %}primary{% else %}default{% endif %} course-box" data-href="#">
            <div class="box-header with-border">
                <h3 class="box-title">
                    {{ course.name }}
                    <small>{{ semester(course.semester_id) }}</small>
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-sm btn-primary" data-toggle="tooltip"
                            data-original-title="编辑" id="toggleEdit">
                        <i class="fa fa-edit"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.outline) }}
                    <p class="form-data">
                        {{ form.outline.data }}
                        {% if outlet_attachment %}
                            <a class="badge bg-green" href="?action=download">
                                <i class="fa fa-file"></i>
                                {{ '大纲附件' + '.' + outlet_attachment.split('.')[-1] }}
                            </a>
                        {% endif %}
                    </p>
                    {{ form.outlet_attachment }}
                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-6">
                                {{ wtf.form_field(form.teamsize_min, placeholder="下限") }}
                                <p class="form-data">{{ form.teamsize_min.data }}</p>
                            </div>
                            <div class="col-xs-6">
                                {{ wtf.form_field(form.teamsize_max, placeholder="上限") }}
                                <p class="form-data">{{ form.teamsize_max.data }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-2">
                                {{ wtf.form_field(form.no_miss, placeholder="0") }}
                                <p class="form-data">
                                    {{ form.no_miss.data }}
                                </p>
                            </div>
                            <div class="col-xs-2">
                                {{ wtf.form_field(form.miss_1, placeholder="0") }}
                                <p class="form-data">{{ form.miss_1.data }}</p>
                            </div>
                            <div class="col-xs-2">
                                {{ wtf.form_field(form.miss_2, placeholder="0") }}
                                <p class="form-data">{{ form.miss_2.data }}</p>
                            </div>
                            <div class="col-xs-2">
                                {{ wtf.form_field(form.miss_3, placeholder="0") }}
                                <p class="form-data">{{ form.miss_3.data }}</p>
                            </div>
                            <div class="col-xs-2">
                                {{ wtf.form_field(form.miss_4, placeholder="0") }}
                                <p class="form-data">{{ form.miss_4.data }}</p>
                            </div>
                            <div class="col-xs-2">
                                {{ wtf.form_field(form.miss_5, placeholder="0") }}
                                <p class="form-data">{{ form.miss_5.data }}</p>
                            </div>
                        </div>
                    </div>
                    <input type="submit" class="form-control btn btn-primary btn-block">
                </form>
            </div>
        </div>
        <!-- /.box-primary -->
    </article>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('.form-control').hide();
        $('#outlet_attachment').hide();
        function toggleState() {
            if ($(this).hasClass('btn-danger')) {
                $(this).removeClass('btn-danger');
                $(this).addClass('btn-primary');
                $('.form-control').hide();
                $('#outlet_attachment').hide();
                $('.form-data').show();
            } else {
                $(this).removeClass('btn-primary');
                $(this).addClass('btn-danger');
                $('.form-control').show();
                $('#outlet_attachment').show();
                $('.form-data').hide();
            }
        }
        $('#toggleEdit').click(toggleState);
    </script>
{% endblock %}

app/templates/teacher/homework.html
{% extends "base_main.html" %}

{% block title %}{{ super() }} - 课程管理{% endblock %}

{% block content_header %}
    <h1>
        {{ course.name }}：作业信息
        <span data-toggle="modal" data-target="#homeworkModal" data-action="add">
            <button type="button" class="btn btn-sm btn-success" data-toggle="tooltip"
                    data-original-title="添加" id="toggleEdit">
                <i class="fa fa-plus"></i>
            </button>
        </span>
    </h1>
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='components/datepicker/css/datepicker.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='components/bootstrap-daterangepicker/daterangepicker.css') }}">
{% endblock %}

{% block breadcrumb %}
    <li><a href="/"><i class="fa fa-dashboard"></i> 主页</a></li>
    <li class="active">作业信息</li>
{% endblock %}

{% block content_main %}
    <article>
        <div class="box box-primary" data-href="#">
            <div class="box-header with-border">
                <h3 class="box-title">
                    作业列表
                </h3>
                <div class="box-tools pull-right">
                    <a href="{{ url_for('teacher.get_teamhomework_all',
                            course_id=course_id) }}"
                       class="btn btn-dropbox btn-sm">下载完整提交状态</a>
                </div>
            </div>
            <div class="box-body no-padding">
                <table class="table table-hover table-stripped">
                    <thead>
                        <tr>
                            <th>作业名</th>
                            <th>时间</th>
                        </tr>
                    </thead>
                    <thead>
                        {% for homework in homeworks %}
                            <tr>
                                <td>
                                    <a href="{{ url_for('teacher.homework_detail', course_id=course_id, homework_id=homework.id) }}"">
                                        {{ homework.name }}
                                    </a>
                                </td>
                                <td>
                                    <time>{{ homework.begin_time.strftime(('%m/%d/%Y %H:%M')) }}</time>
                                    到
                                    <time>{{ homework.end_time.strftime(('%m/%d/%Y %H:%M')) }}</time>
                                </td>
                            </tr>
                        {% endfor %}
                    </thead>
                </table>
            </div>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="homeworkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="homeworkModalLabel">
                        添加作业
                    </h4>
                </div>
                <div class="modal-body">
                    <form method="post" id="form" action="">
                        {{ form.hidden_tag() }}
                        {{ wtf.form_field(form.name) }}
                        {{ wtf.form_field(form.base_requirement) }}
                        {{ wtf.form_field(form.time) }}
                        {{ wtf.form_field(form.weight, type="number", min="0", max="100") }}
                        {{ wtf.form_field(form.max_submit_attempts, type="number") }}
                        <input type="submit" value="提交" class="btn btn-primary btn-block">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
{{ super() }}
    <!-- bootstrap datepicker -->
    <script src="{{ url_for('static', filename='components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <script>
        $('#time').daterangepicker({
            timePicker: true,
            timePicker24Hour: true,
            timePickerIncrement: 30,
            locale: {
                format: 'MM/DD/YYYY HH:mm'
            }
        });
    </script>
{% endblock %}

app/templates/teacher/index.html
{% extends "base_main.html" %}

{% block title %}{{ super() }} - 课程管理{% endblock %}

{% block content_header %}
    <h1>课程选择
        <small>请选择一节课</small>
    </h1>
{% endblock %}

{% block breadcrumb %}
    <li class="active"><a href="/"><i class="fa fa-dashboard"></i> 主页</a></li>
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        .course-box {
            cursor: pointer;
            user-select: none;
        }
    </style>
{% endblock %}

{% block content_main %}
    <article>
        <div class="row">
        {% for course in courses %}
                <div class="col-xs-6">
                    <div class="box box-{% if course.status %}primary{% else %}default{% endif %} course-box" data-href="/teacher/{{ course.id }}/course">
                        <div class="box-header with-border">
                            <h3 class="box-title">
                                {{ course.name }}
                                <small>{{ (course.semester_id / 100) | int  }}年第{{ course.semester_id % 100 }}学期</small>
                            </h3>
                            {% if not course.status %}
                                <div class="box-tools pull-right">
                                    <button data-download="{{ url_for('teacher.see_class_before', course_id = course.id) }}"
                                        class="btn btn-success btn-sm">下载往期课程作业</button>
                                </div>
                            {% endif %}
                        </div>
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>上课地点</dt>
                                <dd>{{ course.place | safe }}</dd>
                                <dt>开课状态</dt>
                                <dd>{% if course.status %}开课{% else %}结课{% endif %}</dd>
                                <dt>教师</dt>
                                <dd>
                                    {% for teacher in course.teachers %}
                                        {{ teacher.name | safe }}
                                    {% endfor %}
                                </dd>
                                <dt>学生人数</dt>
                                <dd>{{ course.students | length }}</dd>
                            </dl>
                        </div>
                    </div>
                    <!-- /.box-primary -->
                </div>
            {% if loop.index % 2 == 0 and not loop.last %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
        </div>
    </article>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
        $('.course-box').click(function () {
            window.location.href = $(this).data('href');
        });
        $('[data-download]').click(function (ev) {
            ev.stopPropagation();
            window.location.href = $(this).data('download');
        });
    </script>
{% endblock %}

app/templates/teacher/manage_attendance.html
{% extends "base_main.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ super() }} - 课程管理{% endblock %}

{% block content_header %}
    <h1>{{ course.name }}：签到信息
        <a href="{{ url_for('teacher.get_attendence_all',
            course_id=course_id) }}"
            class="btn btn-success btn-sm">下载签到报表</a>
    </h1>
{% endblock %}

{% block body_attribs %} class="hold-transition skin-black sidebar-mini" {% if form.errors %}onload="edit_state()"{% endif %}{% endblock %}

{% block breadcrumb %}
    <li><a href="/"><i class="fa fa-dashboard"></i> 主页</a></li>
    <li class="active">课程信息</li>
{% endblock %}

{% block content_main %}
    <article>
        {% for attendance in attendance_list %}
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">
                         签到信息
                    </h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    {{ attendance.info | safe }}
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <dl class="dl-horizontal">
                        <dt>开始时间</dt>
                        <dd>{{ attendance.time_begin }}</dd>
                        <dt>结束时间</dt>
                        <dd>{{ attendance.time_end }}</dd>
                    </dl>
{#                    <div class="col-xs-6">#}
{#                        <div class="panel box box-success">#}
{#                            <div class="box-header with-border">#}
{#                                <h4 class="box-title">#}
{#                                    <a data-toggle="collapse" data-parent="#accordion" href="#student{{ course.id }}"#}
{#                                       class="collapsed" aria-expanded="false">#}
{#                                        学生#}
{#                                    </a>#}
{#                                </h4>#}
{#                            </div>#}
{#                            <div id="student{{ course.id }}" class="panel-collapse collapse" aria-expanded="false">#}
{#                                <div class="box-body no-padding">#}
{#                                    <table class="table">#}
{#                                        <tbody>#}
{#                                        {% for student in student_attendance_list %}#}
{#                                            <tr>#}
{#                                                <td>{{ student.id }}</td>#}
{#                                                <td>{{ student.name }}</td>#}
{#                                            </tr>#}
{#                                        {% endfor %}#}
{#                                        </tbody>#}
{#                                    </table>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}


                </div>
            </div>
        {% endfor %}
        <!-- /.box -->
        <div class="box box-info collapsed-box">
            <div class="box-header with-border">
                <h3 class="box-title">
                    添加签到
                </h3>
                <div class="box-tools pull-right">
                    <button type="button" id="collapse_button" class="btn btn-sm btn-primary" data-widget="collapse">
                        <i class="fa fa-plus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <form method="post" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_errors(form) }}

                    {{ wtf.form_field(form.info) }}
                    {{ wtf.form_field(form.time_delta, placeholder="单位：分钟 e.g. 5") }}

                    <button type="submit" class="btn btn-primary btn-block btn-flat">提交</button>
                </form>
            </div>
        </div>
    </article>
{% endblock %}

{% block scripts %}
{{ super() }}
    <script>
        $('#credit').attr('type', 'number');
        function edit_state() {
            $('#collapse_button').click();
        }
    </script>
{% endblock %}